types:
  - name: sokan
    nname: s.
    forms:
      - name: topic
        nname: top
        default: "%zu"
      - name: direct
        nname: dir
        default: "%su"
      - name: instrumental
        nname: inst
        default: "%sem"
      - name: allative
        nname: alla
        default: "%ko"
      - name: accusative
        nname: accu
        default: "%bu"
      - name: dative
        nname: dat
        default: "%do"
      - name: position
        nname: pos
        default: "%cu"
      - name: cominative
        nname: com
        default: "%kaw"
      - name: anti-cominative
        nname: ant
        default: "%now"
      - name: ablative
        nname: abla
        default: "%'je"
      - name: terminative
        nname: term
        default: "%'we"
  - name: burab
    nname: b.
  - name: mosrab
    nname: m.
  - name: gasaru
    nname: g.
  - name: unekin
    nname: u.
