dictionaries:
  - abstract_behaviour.yml
  - artificial.yml
  - auxiliary_words.yml
  - behaviour.yml
  - body.yml
  - colors.yml
  - direction.yml
  - feeling.yml
  - krin.yml
  - life.yml
  - logic.yml
  - nature.yml
  - numerals.yml
  - physical_property.yml
  - pov.yml
  - pronoun.yml
  - shape.yml
  - status.yml
  - time.yml
  - unclassified_new.yml
types:
  - name: sokan
    nname: s.
    forms:
      - name: topic
        nname: top
        default: "%zu"
      - name: nominative
        nname: nom
        default: "%su"
      - name: instrumental
        nname: inst
        default: "%sem"
      - name: allative
        nname: alla
        default: "%ko"
      - name: accusative
        nname: accu
        default: "%bu"
      - name: dative
        nname: dat
        default: "%do"
      - name: position
        nname: pos
        default: "%cu"
      - name: cominative
        nname: com
        default: "%kaf"
      - name: anti-cominative
        nname: ant
        default: "%nof"
      - name: ablative
        nname: abla
        default: "%ye"
      - name: terminative
        nname: term
        default: "%we"
  - name: burab
    nname: b.
  - name: mosrab
    nname: m.
  - name: gasaru
    nname: g.
  - name: unekin
    nname: u.
